apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-server 
spec:
  selector:
    app: {{ .Release.Name }}-server
  ports:
  - protocol: "TCP"
    name: web
    port: 7000
    targetPort: 5000
    
