apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  ports:
  - protocol: "TCP"
    port: 7000
    targetPort: 5000
    
