# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENVIRONMENT: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    -
      uses: jmagnusson/deploy-helm-gke-action@v1
      with:
          docker-image-repo: myshokpavlo/simple_server     #done     info: Docker image
          docker-image-tag: simple_server                  #done     info: Docker image tag
          helm-release-name: testdeploy-app                #done     info: Name of helm release, type of: ${{ env.APP_NAME }}
          helm-chart-path: ./charts/mytestchart            #done     info: Where the Helm chart resides, type of: ./charts/${{ env.APP_NAME }}
          helm-vars-folder: ./charts/mytestchart           #done     info: This folder must contain the file values.yaml
          gke-project: ${{ secrets.GKE_PROJECT }}          #done
          gke-cluster: primary                             #done
          gke-zone: ${{ secrets.GKE_ZONE }}                #done
          gke-sa-key: ${{ secrets.GKE_SA_KEY }}            #done
          
          
          
# errors:      1. No Helm chart found at ./charts/releases/Chart.yaml  2. No Helm chart found at charts/mytestchart/Chart.yaml  3. unable to get kubernetes config: invalid character ':' after top-level value ....gke kubeconfig  4. ivalid release name
#fix: 1. change chart-path to git folder      2. enter correct folder 3. update all secrets 



          
          
          
          
          
          
